// Multi-format export helpers (dependency-free).
export { downloadCsv, downloadCsvMulti } from './export-csv';
import type { ExportMeta } from './export-csv';
export type { ExportMeta } from './export-csv';

function triggerDownload(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

const esc = (s: unknown) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

function xlsSheetXml(name: string, headers: string[], rows: (string | number)[][]) {
  const cell = (v: string | number) =>
    typeof v === 'number'
      ? `<Cell><Data ss:Type="Number">${v}</Data></Cell>`
      : `<Cell><Data ss:Type="String">${esc(v)}</Data></Cell>`;
  const hdr = (v: string) => `<Cell ss:StyleID="h"><Data ss:Type="String">${esc(v)}</Data></Cell>`;
  return `<Worksheet ss:Name="${esc(name)}"><Table>` +
    `<Row>${headers.map(hdr).join('')}</Row>` +
    rows.map((r) => `<Row>${r.map(cell).join('')}</Row>`).join('') +
    `</Table></Worksheet>`;
}

/** Excel-compatible SpreadsheetML workbook (.xls) — opens natively in Excel. */
export function downloadXls(name: string, headers: string[], rows: (string | number)[][], meta?: ExportMeta) {
  downloadXlsMulti(name, [{ name: 'Export', headers, rows }], meta);
}

/** Same workbook format, one worksheet tab per section — every table lands in the same file
 *  instead of forcing a one-table-at-a-time export. Excel sheet names are capped at 31 chars.
 *  When `meta` is given, a leading "Report Info" sheet carries generated-at/by and applied filters. */
export function downloadXlsMulti(name: string, sheets: { name: string; headers: string[]; rows: (string | number)[][] }[], meta?: ExportMeta) {
  const metaSheet = meta ? xlsSheetXml('Report Info', ['Field', 'Value'],
    [['Generated', meta.generatedAt], ['Generated By', meta.generatedBy], ['Filters Applied', meta.scope]]) : '';
  const xml =
    `<?xml version="1.0"?>\n<?mso-application progid="Excel.Sheet"?>\n` +
    `<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">` +
    `<Styles><Style ss:ID="h"><Font ss:Bold="1"/><Interior ss:Color="#0d9488" ss:Pattern="Solid"/></Style></Styles>` +
    metaSheet +
    sheets.map((s) => xlsSheetXml(s.name.slice(0, 31), s.headers, s.rows)).join('') +
    `</Workbook>`;
  triggerDownload(name.endsWith('.xls') ? name : `${name}.xls`, xml, 'application/vnd.ms-excel');
}

/** Open a print-ready view of the table; user saves as PDF. */
export function exportPdf(title: string, headers: string[], rows: (string | number)[][], meta?: ExportMeta) {
  exportPdfMulti(title, [{ label: title, headers, rows }], meta);
}

/** Same print-ready view, with every table rendered in sequence — used when exporting a full
 *  multi-table report instead of a single dataset. */
export function exportPdfMulti(title: string, sections: { label: string; headers: string[]; rows: (string | number)[][] }[], meta?: ExportMeta) {
  const w = window.open('', '_blank');
  if (!w) return;
  const totalRows = sections.reduce((s, sec) => s + sec.rows.length, 0);
  const blocks = sections.map((sec) => {
    const th = sec.headers.map((h) => `<th>${esc(h)}</th>`).join('');
    const body = sec.rows.map((r) => `<tr>${r.map((c) => `<td>${esc(c)}</td>`).join('')}</tr>`).join('');
    return `<h3>${esc(sec.label)}</h3><table><thead><tr>${th}</tr></thead><tbody>${body}</tbody></table>`;
  }).join('');
  const metaLine = meta
    ? `Generated ${esc(meta.generatedAt)} by ${esc(meta.generatedBy)} · Filters: ${esc(meta.scope)} · ${totalRows} rows across ${sections.length} table(s)`
    : `Zyter — generated ${esc(new Date().toLocaleString())} · ${totalRows} rows across ${sections.length} table(s)`;
  w.document.write(`<!doctype html><html><head><title>${esc(title)}</title><style>
    body{font-family:Segoe UI,Arial,sans-serif;color:#1f2937;padding:24px;}
    h2{font-size:18px;margin:0 0 4px;} h3{font-size:14px;margin:22px 0 8px;}
    h3:first-of-type{margin-top:0;}
    .meta{color:#6b7280;font-size:12px;margin-bottom:16px;}
    table{width:100%;border-collapse:collapse;font-size:12px;margin-bottom:8px;}
    th{background:#0d9488;color:#fff;text-align:left;padding:8px 10px;}
    td{padding:7px 10px;border-bottom:1px solid #e5e7eb;}
    tr:nth-child(even) td{background:#f9fafb;}
    @media print{@page{margin:14mm;} h3{break-after:avoid;} table{break-inside:avoid;}}
  </style></head><body><h2>${esc(title)}</h2>
  <div class="meta">${metaLine}</div>
  ${blocks}
  <script>window.onload=function(){setTimeout(function(){window.print();},250);};<\/script>
  </body></html>`);
  w.document.close();
}
