// Build a CSV string and trigger a browser download. No dependencies.

/** Provenance stamped onto an export — which filters were applied, and who/when generated it. */
export interface ExportMeta { generatedAt: string; generatedBy: string; scope: string; }

function cell(v: string | number): string {
  const s = String(v ?? '');
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function metaRows(meta?: ExportMeta): [string, string][] {
  return meta ? [['Generated', meta.generatedAt], ['Generated By', meta.generatedBy], ['Filters Applied', meta.scope]] : [];
}

function triggerCsvDownload(filename: string, lines: string[]): void {
  const blob = new Blob(['﻿' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.csv') ? filename : `${filename}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

export function downloadCsv(filename: string, headers: string[], rows: (string | number)[][], meta?: ExportMeta): void {
  const lines: string[] = [];
  metaRows(meta).forEach(([k, v]) => lines.push(`${cell(k)},${cell(v)}`));
  if (meta) lines.push('');
  lines.push(headers.map(cell).join(','), ...rows.map((r) => r.map(cell).join(',')));
  triggerCsvDownload(filename, lines);
}

/** One CSV file holding every table, each preceded by a "## Label" marker line so the tables stay
 *  distinguishable once opened in a spreadsheet — used when a report has more than one table and
 *  the user wants everything, not a one-table-at-a-time picker. */
export function downloadCsvMulti(filename: string, sections: { label: string; headers: string[]; rows: (string | number)[][] }[], meta?: ExportMeta): void {
  const lines: string[] = [];
  metaRows(meta).forEach(([k, v]) => lines.push(`${cell(k)},${cell(v)}`));
  if (meta) lines.push('');
  sections.forEach((s, i) => {
    if (i > 0) lines.push('');
    lines.push(`## ${s.label}`);
    lines.push(s.headers.map(cell).join(','));
    s.rows.forEach((r) => lines.push(r.map(cell).join(',')));
  });
  triggerCsvDownload(filename, lines);
}
